export const dataMedalers = [
  {
    id: 1,
    profile: {
      name: "arjun samudera ahli fikri",
      city: "kota kediri",
      age: 18,
      gender: "man",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 717.7,
    elevation: 10.1,
    isEdit: false,
  },
  {
    id: 2,
    profile: {
      name: "jhon doe",
      city: "kota malang",
      age: 24,
      gender: "man",
      tagger: "LSILVERKBT",
      imageProfile: "/images/profile-student.jpg",
    },
    average: 313.7,
    elevation: 90.4,
    isEdit: false,
  },
  {
    id: 3,
    profile: {
      name: "david marco",
      city: "kota banyuwangi",
      age: 17,
      gender: "man",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 100.7,
    elevation: 32.4,
    isEdit: false,
  },
  {
    id: 4,
    profile: {
      name: "Suciati Luluk",
      city: "Bjarne Stroustrup",
      age: 45,
      gender: "woman",
      tagger: "LJUNIORKBT",
      imageProfile: "/images/profile-student.jpg",
    },
    average: 95,
    elevation: 100.4,
    isEdit: false,
  },
  {
    id: 5,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 50.5,
    elevation: 30.4,
    isEdit: false,
  },
  {
    id: 6,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 17.5,
    elevation: 110.4,
    isEdit: false,
  },
  {
    id: 7,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 50.5,
    elevation: 150.4,
    isEdit: false,
  },
  {
    id: 8,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 50.5,
    elevation: 9.9,
    isEdit: false,
  },
  {
    id: 9,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 50.5,
    elevation: 7.4,
    isEdit: false,
  },
  {
    id: 10,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 79.5,
    elevation: 77.4,
    isEdit: false,
  },
  {
    id: 11,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 50.5,
    elevation: 12.4,
    isEdit: false,
  },
  {
    id: 12,
    profile: {
      name: "top global",
      city: "kota kediri",
      age: 12,
      gender: "man",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 50.5,
    elevation: 250.4,
    isEdit: false,
  },
  {
    id: 13,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 112.5,
    elevation: 58.4,
    isEdit: false,
  },
  {
    id: 14,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 74.5,
    elevation: 70.4,
    isEdit: false,
  },
  {
    id: 15,
    profile: {
      name: "nafa yasmin nafa hatil unsy",
      city: "kota kediri",
      age: 12,
      gender: "woman",
      tagger: "LGOLDKBT",
      imageProfile: "/images/profile-user.jpg",
    },
    average: 4.5,
    elevation: 40.4,
    isEdit: false,
  },
];
